### ISSUE TITLE
Chocolatey 'install' failure

### ISSUE THREAD

**Issue by PeterDeKeer** [atom/chocolatey#13]
Windows 8. Downloaded Chocolatey as admin, in same screen I try to "cinst Atom"
(cmd ver Microsoft Windows [Version 6.3.9600])

```
Chocolatey (v0.9.8.25) is installing 'Atom' and dependencies. By installing you accept the license for 'Atom' and each dependency you are installing.

Atom v0.113.0
Extracting C:\Users\Peter\AppData\Local\Temp\chocolatey\Atom\AtomInstall.zip to C:\ProgramData\chocolatey\lib\Atom.0.113.0\tools...
Write-Error : Atom did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] This command cannot be run due to the error: The system cannot find the file specified.
-----------------------
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-ChocolateyFailure.ps1:30 char:3
+   Write-Error $errorMessage
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

Write-Error : Package 'Atom v0.113.0' did not install successfully: This command cannot be run due to the error: The system cannot find the file specified.
At C:\ProgramData\chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:90 char:17
+                 Write-Error "Package `'$installedPackageName v$installedPackageV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

The term 'true' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify t
hat the path is correct and try again.
Command 'install' failed (sometimes this indicates a partial failure). Additional info/packages: Atom
```

**Comment by apometron** [comment]
I am trying to update a software and I cant. I generated the debug output. I want to use the GUI.

PS C:\WINDOWS\system32> choco upgrade chocolatey -debug >clip:
out-file : Cannot find drive. A drive with the name 'clip' does not exist.
At line:1 char:1
+ choco upgrade chocolatey -debug >clip:
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (clip:String) [Out-File], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.OutFileCommand
 

PS C:\WINDOWS\system32> 
PS C:\WINDOWS\system32> choco upgrade chocolatey -debug
Chocolatey v0.10.11
Chocolatey is running on Windows v 10.0.17134.0
Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade chocolatey -debug
Received arguments: upgrade chocolatey -debug
The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple 
 check to be sure no sensitive data is shown, especially if copying 
 output to a gist for review.
Configuration: CommandName='upgrade'|CacheLocation='C:\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='False'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='chocolatey'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='chocolatey'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.17134.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.11.0'|
Information.ChocolateyProductVersion='0.10.11'|
Information.FullName='choco, Version=0.10.11.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='apome'|Information.UserDomainName='APOMETRON'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='True'|Features.LogWithoutColor='False'|
Features.VirusCheck='True'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
PinCommand.Command='unknown'|OutdatedCommand.IgnorePinned='False'|
Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
Upgrading the following packages:
chocolatey
By upgrading you accept licenses for the packages.
Current environment values (may contain sensitive data):
  * 'ChocolateyLastPathUpdate'='Fri May 11 22:43:16 2018' ('User')
  * 'ChocolateyToolsLocation'='C:\tools' ('User')
  * 'OneDrive'='C:\Users\apome\OneDrive' ('User')
  * 'Path'=';C:\tools\mingw64\bin;C:\Users\apome\AppData\Local\Microsoft\WindowsApps' ('User')
  * 'TEMP'='C:\Temp' ('User')
  * 'TMP'='C:\Temp' ('User')
  * 'ChocolateyInstall'='C:\ProgramData\chocolatey' ('Machine')
  * 'ComSpec'='G:\utils\TCCLE14X64\tcc.exe' ('Machine')
  * 'DriverData'='C:\Windows\System32\Drivers\DriverData' ('Machine')
  * 'DXSDK_DIR'='C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\' ('Machine')
  * 'GTK_BASEPATH'='C:\Program Files (x86)\GtkSharp\2.12\' ('Machine')
  * 'NUMBER_OF_PROCESSORS'='8' ('Machine')
  * 'OS'='Windows_NT' ('Machine')
  * 'Path'='C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python36\Scripts\;C:\Python36\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Syst
em32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Java\jdk1.8.0_162\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\System32\OpenSSH\' ('Machine')
  * 'PATHEXT'='.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW' ('Machine')
  * 'PROCESSOR_ARCHITECTURE'='AMD64' ('Machine')
  * 'PROCESSOR_IDENTIFIER'='AMD64 Family 21 Model 1 Stepping 2, AuthenticAMD' ('Machine')
  * 'PROCESSOR_LEVEL'='21' ('Machine')
  * 'PROCESSOR_REVISION'='0102' ('Machine')
  * 'PSModulePath'='C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules' ('Machine')
  * 'TEMP'='C:\WINDOWS\TEMP' ('Machine')
  * 'TMP'='C:\WINDOWS\TEMP' ('Machine')
  * 'USERNAME'='SYSTEM' ('Machine')
  * 'windir'='C:\WINDOWS' ('Machine')
chocolatey v0.10.11 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Exiting with 0

PS C:\WINDOWS\system32>
