### ISSUE TITLE
Atom has ShimGen icon in Windows 8.1

### ISSUE THREAD

**Issue by daldr-ntml** [atom/chocolatey#31]
I installed Atom in Windows 8.1 using Chocolatey:

cinst Atom

and did an upgrade:

cup Atom

When I search for Atom on the computer I find 'Atom' with an icon that says 'Shim'. If I pin that to the taskbar, again I see the Shim icon - not the Atom icon. Clicking the icon starts a normal Atom session and adds an Atom icon to the taskbar for the duration of the session.

In Windows 7 I only see the Atom icon.

Is it correct to see the Shim icon in Windows 8.1?

Please see these images:

![taskbar_atom](https://cloud.githubusercontent.com/assets/7724321/4502779/d622c408-4acd-11e4-91be-5fae29135ab9.png)
![search_atom](https://cloud.githubusercontent.com/assets/7724321/4502780/d6471aba-4acd-11e4-80a4-8de5ae329282.png)

**Comment by ferventcoder** [comment]
This is fixed and will be released with a dot release of choco.

**Comment by ferventcoder** [comment]
See https://github.com/chocolatey/shimgen/issues/2 and https://github.com/chocolatey/chocolatey/issues/579 for more details.

**Comment by ferventcoder** [comment]
I pushed a prerelease just now - https://chocolatey.org/packages/chocolatey/0.9.8.29-alpha1
