### ISSUE TITLE
Potential AppVeyor CI issue?

### ISSUE THREAD

**Issue by jugglingnutcase** [atom/chocolatey#36]
i'm getting AppVeyor build failures in a PR for my language grammar: jugglingnutcase/language-powershell#33. You can see the [full build log for one of the failing commits in this link](https://ci.appveyor.com/project/jugglingnutcase/language-powershell/build/94), but here's a relevant snippet:

```
cd %APPVEYOR_BUILD_FOLDER%
apm install
'apm' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

i have [experienced a number of these failures](https://ci.appveyor.com/project/jugglingnutcase/language-powershell/history) and have yet to find one that has failed within the past few days for any other reason. i would expect that apm would be found after a chocolately install, especially because the appveyor file is up-to-date with what atom/ci suggests.

It was working until recently, and the only other package in the atom org that i could find [atom/fuzzaldrin](https://github.com/atom/fuzzaldrin) using an Appveyor.yml file doesn't have any recent builds.

i'm not sure if this is the right place to report this, i checked atom/ci, but i think that this issue may be more relevant here.

If i can be more helpful, please let me know. i've made a couple attempts to track down why this is happening, but they've been fruitless.

**Comment by kevinsawicki** [comment]
Would you mind trying something for me?

Can you try using [this appveyor.yml](https://github.com/atom/wrap-guide/blob/master/appveyor.yml) and see if it works?

I was testing out a fix on that package but for some reason my build is just showing as infinitely queued, https://ci.appveyor.com/project/kevinsawicki/wrap-guide/build/3

**Comment by jugglingnutcase** [comment]
Yeah, I don't mind doing that. I'll let you know how it goes. 

I noticed you had infinite builds too, queued up for months IIRC! Weird.

**Comment by jugglingnutcase** [comment]
Looks much better, [here's a successful build](https://ci.appveyor.com/project/jugglingnutcase/language-powershell/build/102) with your suggested appveyor.yml file.

**Comment by kevinsawicki** [comment]
Okay, 0.177 came out today with some `apm test` fixes and so if you use the new template from https://github.com/atom/ci/blob/master/appveyor.yml things should properly build/test now.

**Comment by jugglingnutcase** [comment]
Thanks! :+1:
