### ISSUE TITLE
Error installing chocolatey

### ISSUE THREAD

**Issue by jalasem** [atom/chocolatey#41]
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
At line:149 char:3
-   $downloader.DownloadFile($url, $file)
-   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : WebException

Extracting C:\Users\ABDUL-~1\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\ABDUL-~1\AppData\Local\Temp\chocolatey\chocInstall...
Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompression = 'false' and call
install again to use 7zip to unzip. Error:
 You cannot call a method on a null-valued expression.
At line:185 char:5
-     throw "Unable to unzip package using built-in compression. Set `$ ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : OperationStopped: (Unable to unzip...ued expression.:String) [], RuntimeException
  - FullyQualifiedErrorId : Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompres
    sion = 'false' and call install again to use 7zip to unzip. Error:
    You cannot call a method on a null-valued expression.

**Comment by ferventcoder** [comment]
Wrong repo - read the error message, it tells you how to fix the issue

**Comment by ferventcoder** [comment]
Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompression = 'false' and call
install again to use 7zip to unzip.

**Comment by jalasem** [comment]
How do I do that?

**Comment by alexcoroza** [comment]
sorry man. Already wasted days figuring out how to set this $env. We're total begginers.

**Comment by 50Wliu** [comment]
Unrelated to ATom.

**Comment by ferventcoder** [comment]
@alexcoroza @jalasem this was just changed back to use the old 7zip download uncompress method. Go give it a shot again.

**Comment by alexcoroza** [comment]
I followed react-native's installation docu on how to install chocolatey and it worked like a charm. I dont know why nativescripts' code doesnt work on my computer. Thanks for the response sir.
